<?php

$form = $this->form;

$this->formElementErrors ()
    ->setMessageOpenFormat ('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">×</button>')
    ->setMessageCloseString ('</div>')
    ->render ($form);


$form->prepare ();

echo $this->form ()->openTag ($form);
echo '<div class="form-group">';
echo $this->formCollection ($form);
echo '</div>';

echo $this->form ()->closeTag ();

?>